### ISSUE TITLE
Creating an Elo game is not intuitive

### ISSUE THREAD

**Issue by vishalkuo** [elovation/elovation#70]
https://github.com/elovation/elovation/blob/473c31eb24ab948efcca33680240de4c86291271/app/models/rater.rb#L14

Involving this line of code here; you cannot create a game unless these specific settings are inputted (2 teams and 1 player per team). If the elo option is selected; the game settings should default to this. 

Is this expected behaviour or can I fix this

**Comment by christoshrousis** [comment]
I implemented a solution for this on my personal account, I just made it prepopulate and hide the fields in the new game form that weren't relevant.  If you want to build something like that into it, please feel free to make a pull request, otherwise I will tackle it in my own time when I get a chance.

The modelling doesn't need to change because elo is 1v1. If you think you can come up with a better modelling solution, please feel free to make a pull request.

Thanks for the feedback.
